GET http://localhost:3000/hospital
###
GET http://localhost:3000/hospital/hospital0000001
###
POST http://localhost:3000/hospital
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6InJhaG1hbnN5YWhmYXJpc0BnbWFpbC5jb20iLCJpYXQiOjE3MDc1NjYxNTcsImV4cCI6MTcwNzU4MDU1N30.v8dj1-BWWqRSeaKdsseN72mVo8PkDuHWiSbS8WJ9N-M

{
    "hospital_id": "hospital0000001",
    "name": "RS Merpatiku wow",
    "address": "Jln. Merpatiku wow"
}
###
PATCH http://localhost:3000/hospital/hospital0000001
Content-Type: application/json

{
    "address": "Jln. Merpatikuy no 123"
}
###
DELETE http://localhost:3000/hospital/hospital0000001
###
POST http://157.230.37.110:3000/hospital
Content-Type: application/json

{
    "name": "RS Merpatikuy",
    "address": "Jln. Merpatikuy"
}