GET http://localhost:3000/admin
Api-Key: LegusApex123
###
GET http://localhost:3000/admin/admin0000002
Api-Key: LegusApex123
###
POST http://localhost:3000/admin
Content-Type: application/json
Api-Key: LegusApex123

{
    "name": "Test Nama Admin Adin",
    "hospital_id": "hospital0000010",
    "email": "adin@email.com",
    "password": "321admin"
}
###
PATCH http://localhost:3000/admin/admin0000001
Content-Type: application/json

{
    "name": "Test Nama Admin Simpson",
    "email": "adin123@email.com",
    "password": "ganti123"
}
###
DELETE  http://localhost:3000/admin/admin0000001
Api-Key: LegusApex123
###
GET http://157.230.37.110:3000/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6InByb3RlbEBwcm90ZWwuY29tIiwiaWF0IjoxNzA3NjQxMDk0LCJleHAiOjE3MDc2NTU0OTR9.Q0TC_q0rUVHoexnQe7pyf0e7ytW4SBmCAiw174UqxMs
