GET http://localhost:3000/incubator
Api-Key: ProtelLegusApex
###
GET http://localhost:3000/incubator/wow id
###
POST http://localhost:3000/incubator
Content-Type: application/json

{
    "name": "Nama Bayi",
    "birth_date": "10/09/2008 10:59",
    "gender": "Male",
    "parents": ["Aldi", "Zoro", "Herman"],
    "baby_id": "baby0000001",
    "admin_id": "admin0000001"
}
###
POST http://localhost:3000/incubator
Content-Type: application/json

{
    "name": "Test Nama Incubator Ruang A236"
}
###
PATCH http://localhost:3000/incubator/incubator0000001
Content-Type: application/json

{
    "birth_date": "10/09/2008 01:59",
    "baby_id": "baby0000002",
    "parents": []
}
###
PATCH http://localhost:3000/incubator/incubator0000001/add-parents
Content-Type: application/json

{
    "parents": ["Tom", "Dick", "Harry", "Bahamas"]
}
###
PATCH http://localhost:3000/incubator/incubator0000001/remove-parents
Content-Type: application/json

{
    "parents": ["Tom", "Dick", "Harry", "Bahamas", "Yolo"]
}
###
DELETE http://localhost:3000/incubator/wowid
###
GET http://157.230.37.110:3000/incubator/nice_id
###
POST http://157.230.37.110:3000/incubator
Content-Type: application/json

{
    "name": "Nama Bayi 3",
    "birth_date": "2023-09-03T03:00:00.000Z",
    "gender": "Male",
    "parents": ["Halo"],
    "baby_id": "baby0000001",
    "admin_id": "admin0000001",
    "date_created": "2023-09-03T03:00:00.000Z"
}
###
DELETE http://157.230.37.110:3000/incubator/incubator0000001